#ifndef LGLZ_OPS_DELIMS
#define LGLZ_OPS_DELIMS

#define LGLZ_DELIM_PAREN_OPEN    '('
#define LGLZ_DELIM_PAREN_CLOSE   ')'
#define LGLZ_DELIM_BRACKET_OPEN  '['
#define LGLZ_DELIM_BRACKET_CLOSE ']'
#define LGLZ_DELIM_BRACE_OPEN    '{'
#define LGLZ_DELIM_BRACE_CLOSE   '}'
#define LGLZ_DELIM_COLON ':'
#define LGLZ_DELIM_QUOTE_SINGLE '\''
#define LGLZ_DELIM_QUOTE_DOUBLE '\"'
#define LGLZ_DELIM_EQUALS '='
#define LGLZ_DELIM_SEMICOLON ';'
#define LGLZ_DELIM_COMMENT '#'

#define isDelim(D) (\
    D==LGLZ_DELIM_PAREN_OPEN ||\
    D==LGLZ_DELIM_PAREN_CLOSE ||\
    D==LGLZ_DELIM_BRACKET_OPEN ||\
    D==LGLZ_DELIM_BRACKET_CLOSE ||\
    D==LGLZ_DELIM_BRACE_OPEN ||\
    D==LGLZ_DELIM_BRACE_CLOSE ||\
    D==LGLZ_DELIM_COLON ||\
    D==LGLZ_DELIM_QUOTE_SINGLE ||\
    D==LGLZ_DELIM_QUOTE_DOUBLE ||\
    D==LGLZ_DELIM_EQUALS ||\
    D==LGLZ_DELIM_SEMICOLON ||\
    0\
)

#define LGLZ_OP_ARROW "->"

#endif /* LGLZ_OPS_DELIMS */